
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import entity.DatTruoc;
import java.awt.Component;
import java.text.DecimalFormat;
import java.text.Format;
import java.text.SimpleDateFormat;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author Octob
 */
public class formDatTruoc extends javax.swing.JPanel implements ListCellRenderer<DatTruoc>{

    /**
     * Creates new form formTieuDe
     */
    public formDatTruoc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFormDVD = new javax.swing.JPanel();
        lbImg = new javax.swing.JLabel();
        lbSoLuong = new javax.swing.JLabel();
        lbTieuDe_KH = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbNgayMuon = new javax.swing.JLabel();
        lbNgayTra = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(730, 120));

        pnlFormDVD.setBackground(new java.awt.Color(255, 255, 255));
        pnlFormDVD.setPreferredSize(new java.awt.Dimension(730, 120));
        pnlFormDVD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbImg.setPreferredSize(new java.awt.Dimension(75, 40));
        pnlFormDVD.add(lbImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lbSoLuong.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbSoLuong.setForeground(new java.awt.Color(0, 0, 0));
        lbSoLuong.setText("10");
        pnlFormDVD.add(lbSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 30, 20));

        lbTieuDe_KH.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbTieuDe_KH.setForeground(new java.awt.Color(0, 0, 0));
        lbTieuDe_KH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/img/green.png"))); // NOI18N
        lbTieuDe_KH.setText("Dế mèn phiêu lưu ký");
        pnlFormDVD.add(lbTieuDe_KH, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 510, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/img/number_Count.png"))); // NOI18N
        jLabel4.setText("Số lượng:");
        pnlFormDVD.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 80, 20));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(730, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        pnlFormDVD.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 119, -1, -1));

        lbNgayMuon.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbNgayMuon.setForeground(new java.awt.Color(0, 0, 0));
        pnlFormDVD.add(lbNgayMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 100, 20));

        lbNgayTra.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbNgayTra.setForeground(new java.awt.Color(0, 0, 0));
        pnlFormDVD.add(lbNgayTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 100, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFormDVD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFormDVD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbImg;
    private javax.swing.JLabel lbNgayMuon;
    private javax.swing.JLabel lbNgayTra;
    private javax.swing.JLabel lbSoLuong;
    private javax.swing.JLabel lbTieuDe_KH;
    private javax.swing.JPanel pnlFormDVD;
    // End of variables declaration//GEN-END:variables
    Format ft_ngay = new SimpleDateFormat("dd-MM-yyyy"); 
    DecimalFormat ft_tien = new DecimalFormat("###,###,###" +" VNĐ");

    @Override
    public Component getListCellRendererComponent(JList<? extends DatTruoc> list, DatTruoc value, int index, boolean isSelected, boolean cellHasFocus) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
