/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;


import entity.HoaDon;
import entity.TieuDe;
import java.awt.Color;
import java.awt.Component;
import java.text.DecimalFormat;
import java.text.Format;
import java.text.SimpleDateFormat;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author Octob
 */
public class formTienPhat extends javax.swing.JPanel implements ListCellRenderer<HoaDon>{

    /**
     * Creates new form formTieuDe
     */
    public formTienPhat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFormDVD = new javax.swing.JPanel();
        lbSoNgay = new javax.swing.JLabel();
        lbTenKH = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbDVD = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbTongTien = new javax.swing.JLabel();
        lbMaKH = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(730, 50));

        pnlFormDVD.setBackground(new java.awt.Color(255, 255, 255));
        pnlFormDVD.setPreferredSize(new java.awt.Dimension(730, 50));
        pnlFormDVD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbSoNgay.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbSoNgay.setText("10");
        pnlFormDVD.add(lbSoNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 30, 20));

        lbTenKH.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbTenKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/img/green.png"))); // NOI18N
        lbTenKH.setText("Nguyễn Văn A");
        pnlFormDVD.add(lbTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 230, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/img/number_Count.png"))); // NOI18N
        jLabel4.setText("Số ngày");
        pnlFormDVD.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 80, 20));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(730, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        pnlFormDVD.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 49, -1, -1));

        lbDVD.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pnlFormDVD.add(lbDVD, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 280, 20));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/img/dvd.png"))); // NOI18N
        pnlFormDVD.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 30, 20));

        lbTongTien.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbTongTien.setForeground(new java.awt.Color(204, 0, 51));
        lbTongTien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/img/coins.png"))); // NOI18N
        lbTongTien.setText("500.000VND");
        pnlFormDVD.add(lbTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 20));

        lbMaKH.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lbMaKH.setForeground(new java.awt.Color(255, 51, 51));
        lbMaKH.setText("jLabel1");
        pnlFormDVD.add(lbMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 70, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFormDVD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFormDVD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbDVD;
    private javax.swing.JLabel lbMaKH;
    private javax.swing.JLabel lbSoNgay;
    private javax.swing.JLabel lbTenKH;
    private javax.swing.JLabel lbTongTien;
    private javax.swing.JPanel pnlFormDVD;
    // End of variables declaration//GEN-END:variables
    Format ft_ngay = new SimpleDateFormat("dd-MM-yyyy"); 
    DecimalFormat ft_tien = new DecimalFormat("###,###,###" +" VNĐ");
//    public Component getListCellRendererComponent(JList<? extends ChiTietHoaDon> list, ChiTietHoaDon value, int index, boolean isSelected, boolean cellHasFocus) {
//        lbTenKH.setText(value.getHdMa().getKhMa().getKhHoVaTen());
//        lbTongTien.setText(Double.toString(value.getPtMa().getPtTienPhat()));
//        lbSoNgay.setText(Double.toString(value.getPtMa().getPtSoNgay()));
//        lbDVD.setText(value.getDvdMa().getTdMa().getTdTenTD());
//        if (isSelected) {
//            pnlFormDVD.setBackground(new Color(255,204,102));
//         }else{
//            pnlFormDVD.setBackground(Color.WHITE);
//        }
//        return this;
//    }

    @Override
    public Component getListCellRendererComponent(JList<? extends HoaDon> list, HoaDon value, int index, boolean isSelected, boolean cellHasFocus) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
