/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import entity.Dvd;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author Đèn Đom Đóm <BinGii901>>
 */
public class formDVD extends javax.swing.JPanel implements ListCellRenderer<Dvd> {

    /**
     * Creates new form formTieuDe
     */
    public formDVD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFormDVD = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbName = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(730, 60));

        pnlFormDVD.setBackground(new java.awt.Color(255, 255, 255));
        pnlFormDVD.setPreferredSize(new java.awt.Dimension(730, 60));
        pnlFormDVD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(730, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        pnlFormDVD.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 59, -1, -1));

        lbName.setBackground(new java.awt.Color(0, 0, 0));
        lbName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbName.setForeground(new java.awt.Color(0, 0, 0));
        lbName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/img/dvd.png"))); // NOI18N
        lbName.setText("DVD01: Đi chơi không mậy");
        pnlFormDVD.add(lbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 4, 420, 30));

        lbStatus.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbStatus.setForeground(new java.awt.Color(51, 51, 51));
        lbStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/img/green.png"))); // NOI18N
        lbStatus.setText("Đang trống");
        pnlFormDVD.add(lbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 34, 700, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFormDVD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFormDVD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JPanel pnlFormDVD;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends Dvd> list, Dvd value, int index, boolean isSelected, boolean cellHasFocus) {
        lbName.setText(value.getDvdMa() + ": " + value.getTdMa().getTdTenTD());
        if (value.getDvdTrangThai() == 1) {
            lbStatus.setText("Đang trên kệ");
        } else if (value.getDvdTrangThai()== 2) {
            lbStatus.setText("Đang cho thuê");
        } else if (value.getDvdTrangThai() == 3) {
            lbStatus.setText("Đang đặc trước");
        } else {
            lbStatus.setText("Huỷ");
        }
        if (isSelected) {
            pnlFormDVD.setBackground(new Color(255, 204, 102));
        } else {
            pnlFormDVD.setBackground(Color.WHITE);
        }
        if (value.getDvdTrangThai()== 1) {
            lbStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/img/green.png")));
        } else {
            lbStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/img/red.png")));
        }
        return this;
    }

   

}
