/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import entity.KhachHang;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;


/**
 *
 * @author Đèn Đom Đóm <BinGii901>
 */
public class formKhachHang extends javax.swing.JPanel implements ListCellRenderer<KhachHang> {

    /**
     * Creates new form formTieuDe
     */
    public formKhachHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFormDVD = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbName = new javax.swing.JLabel();
        lbLocation = new javax.swing.JLabel();
        lbCall = new javax.swing.JLabel();
        lbID = new javax.swing.JLabel();
        lbStatusKH = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(730, 60));

        pnlFormDVD.setBackground(new java.awt.Color(255, 255, 255));
        pnlFormDVD.setPreferredSize(new java.awt.Dimension(730, 60));
        pnlFormDVD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(730, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        pnlFormDVD.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 59, -1, -1));

        lbName.setBackground(new java.awt.Color(0, 0, 0));
        lbName.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lbName.setForeground(new java.awt.Color(51, 51, 51));
        lbName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/img/name.png"))); // NOI18N
        lbName.setText("Nguyễn Văn A");
        pnlFormDVD.add(lbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 4, 420, 30));

        lbLocation.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbLocation.setForeground(new java.awt.Color(51, 51, 51));
        lbLocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/img/maps-and-flags.png"))); // NOI18N
        lbLocation.setText("jLabel2");
        pnlFormDVD.add(lbLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 34, 420, 20));

        lbCall.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbCall.setForeground(new java.awt.Color(51, 51, 51));
        lbCall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/img/telephone.png"))); // NOI18N
        lbCall.setText("jLabel2");
        pnlFormDVD.add(lbCall, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 34, 160, 20));

        lbID.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lbID.setForeground(new java.awt.Color(204, 0, 51));
        lbID.setText("KH01");
        pnlFormDVD.add(lbID, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 10, 60, -1));

        lbStatusKH.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbStatusKH.setForeground(new java.awt.Color(51, 51, 51));
        lbStatusKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/img/telephone.png"))); // NOI18N
        lbStatusKH.setText("jLabel2");
        pnlFormDVD.add(lbStatusKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 34, 110, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFormDVD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFormDVD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbCall;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbLocation;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbStatusKH;
    private javax.swing.JPanel pnlFormDVD;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends KhachHang> list, KhachHang value, int index, boolean isSelected, boolean cellHasFocus) {
        lbName.setText(value.getKhHoVaTen());
        lbCall.setText(value.getKhSDT().replaceFirst("(\\d{3})(\\d{3})(\\d+)", "($1)-$2-$3"));
        lbLocation.setText(value.getKhDiaChi());
        lbID.setText(value.getKhMa());
        if (isSelected) {
            pnlFormDVD.setBackground(new Color(255, 204, 102));
        } else {
            pnlFormDVD.setBackground(Color.WHITE);
        }
        if (value.getKhTinhTrang() == true) {
            lbStatusKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/img/green.png")));
            lbStatusKH.setText("Hoạt động");
        } else {
            lbStatusKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/img/red.png")));
            lbStatusKH.setText("Đã đóng");
        }
        return this;
    }

}
